### ISSUE TITLE
Mobile - Calendar Navigation

### ISSUE THREAD

**Issue by afzalch** [coffeexcode/capstone#37]
Description:
Unable to scroll consistently through calendar to see future events. The transition from the start of the month to end of the month is abrupt and consistently occurs when scrolling fast. In addition, once you have reached the end of the month, it is impossible to scroll up to go to the beginning of the month and you must manually go to calendar to go to the beginning.

Severity:
Medium

Environment:
Android Device
Expo Go App using provided login

Expected Result:
Expect to be able to smoothly navigate between days of the month

Actual Result:
Unable to smoothly navigate to the days in the middle of the month and unable to scroll back to the beginning of the month after reaching the end

https://user-images.githubusercontent.com/8367234/109259011-66b1eb00-77c9-11eb-8b55-eebcaab00ac7.mp4

**Comment by enricoflorentino** [comment]
Known issue with calendar react native library that is being used
