### ISSUE TITLE
Mobile - Events Date Scheme

### ISSUE THREAD

**Issue by afzalch** [coffeexcode/capstone#38]
Description
The format of date and time for events is rather unusual and should be tweaked to improve readability

Severity
Low

Environment
Android Device
Expo Go App using provided login

Expected
19:36:08 Fri March 26, 2021 - 21:36:08 Fri March 26, 2021

Actual
Fri March 26 19:36:08 2021 - Fri March 26 21:36:08 2021

Screenshot
![Events-dating scheme](https://user-images.githubusercontent.com/8367234/109260574-6109d480-77cc-11eb-84f1-b93969ae14af.jpg)

**Comment by enricoflorentino** [comment]
Invalid date format is an issue native to Android, noted for future development, if possible
