### ISSUE TITLE
Mobile - UI buttons missing text

### ISSUE THREAD

**Issue by afzalch** [coffeexcode/capstone#39]
Description
Numerous buttons in the mobile app are missing the last character

Severity
Moderate

Environment
Android Device
Expo Go

Screenshot
![login](https://user-images.githubusercontent.com/8367234/109265142-13916580-77d4-11eb-88b2-73da404c9977.jpg)
![profile](https://user-images.githubusercontent.com/8367234/109265144-1429fc00-77d4-11eb-8322-28199ca46790.jpg)
![home](https://user-images.githubusercontent.com/8367234/109265146-1429fc00-77d4-11eb-932a-13bb5bb21ba8.jpg)

**Comment by enricoflorentino** [comment]
Issue specific to One Plus phones, will note for future changes.
