### ISSUE TITLE
Website - Searching registrations, someones name matches a status or id.

### ISSUE THREAD

**Issue by teemh** [coffeexcode/capstone#44]
Using Ubuntu VM and FireFox.

Pretty minor bug. I changed the name of one of the registrations to "Accepted Kuvalis". If you search for Accepted, their name will show up even though they Pending. Might just mark Accepted, Pending and Rejected as special words that won't search user's name.

![image](https://user-images.githubusercontent.com/59770668/109400831-f74b1100-7918-11eb-818e-6ea2c85a72dc.png)

This might also affect name and ids. Even though, it's unlikely that an id has a name in it.

**Comment by edavidj** [comment]
The search functionality isn't necessarily for searching the status alone, but a keyword in any of the columns. This way you can search for a person or id if needed (albeit that is a niche use case).

Closing this issue as it's not something we will address, that said including a categorized search bar would be a neat feature to add, so we'll note that for future development.
