### ISSUE TITLE
Mobile - App logo appears quite small on splash screen

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [coffeexcode/capstone#45]
During the initial app load using Expo (tested on Android using Google Pixel 4 XL - 19:9 6.3" display), the app icon on the splash screen appears quite small to the point of barely being able to discern the logo, as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/25377268/109407725-35642700-7951-11eb-8c47-5bdf32270708.png)

The following two image assets, and possibly others, store the logo in a very small size and should perhaps be regenerated:
```
mobile/assets/splash.png
mobile/assets/images/icon_donut.png
```

Severity: Medium
Priority: Medium

**Comment by enricoflorentino** [comment]
Clients won't be exposed to development side, removed the small asset
