### ISSUE TITLE
Mobile - 'Camera permissions denied' while initializing camera

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [coffeexcode/capstone#46]
Steps to reproduce:
1. Ensure camera permissions have already been granted.
2. Start from 'View as' screen.
3. Select either Organizer or Sponsor.
4. Select Scan on bottom tab navigator.
5. Observe for few seconds while loading.

Expected behaviour: Message displayed with appropriate subtext while camera and viewfinder are being initialized.

Actual behaviour: 'Camera permissions defined' message is displayed before the camera viewfinder does appear.
![image](https://user-images.githubusercontent.com/25377268/109408144-a2c58700-7954-11eb-8577-aee0f692521c.png)

Device: Google Pixel 4 XL running Android 11

Severity: Low
Priority: Low

**Comment by enricoflorentino** [comment]
Message has been changed, thanks!
