### ISSUE TITLE
Mobile - Consider adding previous/next week gestures to condensed calendar row

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [coffeexcode/capstone#49]
Specifically with the calendar view when condensed as shown below, there could perhaps be a swipe gesture or similar controls added to quickly move between consecutive weeks within the calendar. Seeing events from the previous or next week with respect to the currently displayed week is a relatively common use case and could be optimized by implementing this feature. Upon swiping, in whichever direction works best with the current implementation, the date can be set to exactly one week earlier or later than the previously selected date to quickly see events on the same day of the week on consecutive weeks.
![image](https://user-images.githubusercontent.com/25377268/109408793-de634f80-795a-11eb-8a86-6fc8e003535a.png)

Device: Google Pixel 4 XL running Android 11

Severity: Low
Priority: Low

**Comment by enricoflorentino** [comment]
Great recommendation although calendar view is from an external lib and out of scope from our project
