### ISSUE TITLE
Mobile - Event details display format/fixes

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [coffeexcode/capstone#50]
There seem to be just a few discrepancies with the event details page which should be fixed by the time it is finalized:
- Date format is quite verbose and repeats Tuesday twice in the below screenshot.
- Location is just an ID/hash for some reason.
- Something is probably meant to be added to the description/caption.
![image](https://user-images.githubusercontent.com/25377268/109409229-ea511080-795e-11eb-9bb6-66086c1084b0.png)

Device: Google Pixel 4 XL running Android 11

Severity: Medium
Priority: Medium

**Comment by enricoflorentino** [comment]
Location ID was because of test data, this is expected. Invalid date format is an issue native to Android, noted for future development, if possible
