### ISSUE TITLE
Mobile - QR scan actions currently lead back to QR scan without performing actions

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [coffeexcode/capstone#51]
Currently, the three buttons shown below for QR scan as an organizer navigate back without performing any action.
![image](https://user-images.githubusercontent.com/25377268/109409485-21c0bc80-7961-11eb-8312-68c88e769285.png)

It would seem that the following snippet in `mobile/src/screens/Organizer/ScanAction.js` is missing its full implementations:
```jsx
      <View style={styles.action}>
        <CAButton testID='scanSignBtn' style={styles.select} title="Sign In" onPress={navigateBack} />
        <Spacer size='md'/>
        <CAButton testID='scanClaimMealBtn' style={styles.select} title="Claim Meal" onPress={navigateBack} />
        <Spacer size='md'/>
        <CAButton testID='scanClaimPrizeBtn' style={styles.select} title="Claim Prize" onPress={navigateBack} />
      </View>
```
I would assume this is still a work in progress, but logging this anyway for tracking.

Severity: Medium
Priority: Medium

**Comment by enricoflorentino** [comment]
Resolved with addition of https://github.com/coffeexcode/capstone/pull/86
