### ISSUE TITLE
Mobile: unable to go back the previous date by rolling up the screen

### ISSUE THREAD

**Issue by liangw27** [coffeexcode/capstone#64]
I am using ios system to run the mobile version of the app. When I roll down the schedule, I can not go back to the previous date by rolling up. I find out the only way to go back the previous date to check schedule is to click on the bottom button of the calender, which is hard to notify. My suggestion is to add the function of going back to the previous dates or a obvious sign to notify users to select a date easily.

**Comment by enricoflorentino** [comment]
This is intended behaviour from https://github.com/wix/react-native-calendars
