### ISSUE TITLE
Mobile: Timezone Issue

### ISSUE THREAD

**Issue by liangw27** [coffeexcode/capstone#65]
I think the timezone issue exists in the event date. In my timezone, it is 11 pm. Thus the registration status of an event between 1pm to 3pm is "The event has ended". However, it is 10 am in Canada time. Assuming using Canada time, this event should be not held until 1pm in Canada. But as an attendee, I could not register anymore since "the event has ended" is displayed in the app. My suggestion is to fix the timezone issue if the app is expected to serve users all over the world.

**Comment by enricoflorentino** [comment]
The app is designed for conferences within NA, however, this will be noted. Thanks!
