### ISSUE TITLE
Mobile: Registration status of an event

### ISSUE THREAD

**Issue by liangw27** [coffeexcode/capstone#68]
As an attendee, it is easy to click on the registration button to register not insterested events by mistake. Everytime when we click on registration button by mistake, we will need to unregister it. I am worried it will mess up the database frequently. Instead of doing that, my suggestion is to create a function to confirm if the user really wants to register this event.

**Comment by enricoflorentino** [comment]
Great recommendation, resolved here: https://github.com/coffeexcode/capstone/pull/86
