### ISSUE TITLE
Website: many unused property

### ISSUE THREAD

**Issue by liangw27** [coffeexcode/capstone#69]
When I try to start the localhost, I receive the warning messages for unused property in terminal. In order to keep it simple, we have better omit unused property. It can also help system maintainers to read and understand more efficiently.

**Comment by edavidj** [comment]
Thanks for the issue, refactoring and linting is important prior to release and we will address it once the project functionality is stable. But as we are still in development process, linting warnings are a low priority at the moment.

Closing, as we track this requirement internally.
