### ISSUE TITLE
Registration API - Docs missing details about expected request body parameters

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [coffeexcode/capstone#71]
From the documentation alone, it isn't immediately clear which fields are expected in the request body.

For example, POST requests to the `/users` endpoint are shown to accept no parameters:
![image](https://user-images.githubusercontent.com/25377268/110220847-7c44a600-7e96-11eb-8990-05cb25c03606.png)

It appears that even random data such as `{ "key": "value" }` in the request body can be specified and it then becomes possible to fill the database with garbage information. This is likely not the intention as the existing data adheres to a particular format.

One could infer that the same fields in the existing data returned via GET request would be acceptable, but this should be documented. Additional information on the data type, meaning, and expected format of these fields would also be helpful.

Severity: Medium
Priority: Medium

**Comment by Jailoodu** [comment]
Added documentation: https://github.com/Jailoodu/RestfulRegistration/commit/dd2c2f15a9a378255b1dfeb8528131f270f5fdff
Closing as a result
