### ISSUE TITLE
Marketing API - GET request returns status code 500

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [coffeexcode/capstone#73]
GET requests to the `/files/download` endpoint return status code 500 with response `{"message": "Internal Server Error"}`.

Expected: status code 200 with response `{"message": "File fetched"}` per the documentation.

Swagger UI:
![image](https://user-images.githubusercontent.com/25377268/110223913-45c25780-7ea5-11eb-861e-790c2f610fee.png)

Postman:
![image](https://user-images.githubusercontent.com/25377268/110223857-e3695700-7ea4-11eb-9adc-b621965c5a11.png)

If there are any additional request headers or fields in the request body expected then this should be documented.

Severity: High
Priority: High

**Comment by Jailoodu** [comment]
Closing due to addition of documentation describing what parameters are required. 
https://github.com/Jailoodu/RestfulMarketing/commit/10c866d96ccbdf813919ebede2d61a703e86f516
