### ISSUE TITLE
Marketing API - Docs missing details about required request body parameters

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [coffeexcode/capstone#74]
Similar to #71, the documentation for POST requests to the `/files/upload` endpoint does not specify the required parameters:
![image](https://user-images.githubusercontent.com/25377268/110224158-3a702b80-7ea7-11eb-8e3e-a590b7acff65.png)

Here, however, not specifying the expected parameters results in a hard failure, as shown below.

Swagger UI:
![image](https://user-images.githubusercontent.com/25377268/110224070-8078bf80-7ea6-11eb-983a-32ef493423cb.png)

Postman:
![image](https://user-images.githubusercontent.com/25377268/110224103-bd44b680-7ea6-11eb-948c-1f0188d47798.png)

Any parameters necessary for file upload should be documented along with the expected format.

Severity: Medium
Priority: Medium

**Comment by Jailoodu** [comment]
Closing issue since I added proper documentation for parameters: https://github.com/Jailoodu/RestfulMarketing/commit/10c866d96ccbdf813919ebede2d61a703e86f516
