### ISSUE TITLE
Website - Not able to run locally on MacOS 11

### ISSUE THREAD

**Issue by lix229** [coffeexcode/capstone#75]
# Summary
Not able to host the website with yarn on MacOS 11.

# Env
- yarn --version: 1.22.10
- macOS version: 11.2.2
- node --version: v15.4.0

# Logs and steps to recreate issue
## Logs
``` bash
❯ yarn install
yarn install v1.22.10
warning package.json: No license field
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 0.59s.
```
``` bash
❯ yarn start
yarn run v1.22.10
warning package.json: No license field
error Command "start" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
## Steps to recreate issue
1. A virtual env was created  // Passed
2. brew install yarn // Passed
3. git clone https://github.com/coffeexcode/capstone.git  // Passed
4. yarn install //Passed with warning, see logs 1
5. yarn start // Error: Command "start" not found. see logs 2

**Comment by edavidj** [comment]
Related to #77 this is the result of not running the command in the correct directory, to start the website you must navigate to `/website` first.

I included a bash command alongside the existing step for navigating to the correct directory for more clarity. Closing.
