### ISSUE TITLE
Mobile - Swipe up on Calendar view incorrectly remove some information from screen

### ISSUE THREAD

**Issue by lix229** [coffeexcode/capstone#80]
# Summary
Swiping up in calendar view when multiple days are loaded, will result in the first day in view being removed from the screen, and swiping down does not negate this behavior.

# Env
- iOS version: 14.4
- Using Expo Go App

# Logs and Issue recreation
## Logs
N/A
## Issue recreation
![IMG_2F9F2436ACEF-1](https://user-images.githubusercontent.com/35265304/110263523-fc493980-7f84-11eb-9e98-7b9b4c0793f0.jpeg)
![IMG_0244](https://user-images.githubusercontent.com/35265304/110263525-ffdcc080-7f84-11eb-91c1-0326db0a8d1b.PNG)

**Comment by enricoflorentino** [comment]
The current date that is selected (as shown on the weekly view) is the 26th therefore the missing information is intended to be missing which is the event on the 23rd. This is expected
