### ISSUE TITLE
Mobile - iPhone - Odd Behaviour When Changing Orientation

### ISSUE THREAD

**Issue by syed-razi** [coffeexcode/capstone#82]
### Description:
When I change the orientation of my phone from portrait to landscape, the information at the top of my iPhone (carrier info., time, battery percentage) disappear. I don't think this should be the case if this app is meant for use only in portrait mode. I tried other apps which are not meant for landscape mode (facebook, instagram) and rotating my phone did not remove the top bar. Also when holding the phone upside down, the top bar reappears oddly, without anything else rotating.

### Environment:
Device: iPhone 7
Software Version: 14.4
Model Number: MN922VC/A

### Steps to Reproduce:
1. Set `Portrait Orientation Lock` to `Off` on iPhone
2. Sign in to ConAssist as attendee
3. Go to QR Code Screen
4. Change phone orientation to landscape
5. Change phone orientation to upside down portrait (180 Deg from portrait mode)

### Actual Result:

1) Holding the phone in landscape removes the top info bar (carrier, time, battery info.), even though nothing else is rotated. 

<img src="https://user-images.githubusercontent.com/25377291/110323038-02b9ce80-7fe2-11eb-9fc8-bae369b7b654.png" width="300">

<img src="https://user-images.githubusercontent.com/25377291/110323660-e702f800-7fe2-11eb-89ef-88fd35612ca3.png" width="500">

2) Holding the phone upside down brings back info bar:

<img src="https://user-images.githubusercontent.com/25377291/110323793-17e32d00-7fe3-11eb-8c4c-91d40f189df9.png" width="300">

### Expected Result:

1) This removal is only to be expected if the app supports a landscape mode, which it seemingly does not, so this info bar should not be removed

2) Holding the phone upside down should either rotate everything 180 degrees or nothing, but the top bar seems to be rotated

### Severity: Medium

**Comment by enricoflorentino** [comment]
Addressed here: https://github.com/coffeexcode/capstone/blob/29b64fe380103d1e98d34a7bde489441a23b0095/mobile/app.json#L7. Thanks!
