### ISSUE TITLE
Mobile - iPhone - Incorrect Registration Description

### ISSUE THREAD

**Issue by syed-razi** [coffeexcode/capstone#84]
### Description:
When I go to `Profile` as either a attendee, organizer, or sponsor I see `"you are registered as a(n) organizer"`

### Environment:
Device: iPhone 7
Software Version: 14.4
Model Number: MN922VC/A

### Steps to Reproduce:
2. Sign in to ConAssist as attendee/sponsor/organizer
3. Go to Profile

### Actual Result:

Showing that I'm registered as an organizer when in fact I'm in the attendee view:

<img src="https://user-images.githubusercontent.com/25377291/110328174-fab15d00-7fe8-11eb-92c1-bd103c9b1e9e.png" width="300">

### Expected Result:

It should show me registered as an attendee

### Severity: Medium

**Comment by enricoflorentino** [comment]
Addressed, thanks!
