### ISSUE TITLE
Mobile - iPhone - Events Shown Don't Match Date Selected

### ISSUE THREAD

**Issue by syed-razi** [coffeexcode/capstone#85]
### Description:
When I select a date to view events on the `Schedule` screen, I see events for dates other than the date that I've chosen

### Environment:
Device: iPhone 7
Software Version: 14.4
Model Number: MN922VC/A

### Steps to Reproduce:
2. Sign in to ConAssist as attendee/sponsor/organizer
3. Go to Schedule
4. Tap on a Date that indicates it has events (i.e with a purple dot underneath)

### Actual Result:

I see results for Thursday even though I've selected Tuesday:

<img src="https://user-images.githubusercontent.com/25377291/110329956-3b11da80-7feb-11eb-8512-5f3de83642b2.png" width="300">

### Expected Result:

I should only be shown events for the date that I've selected

### Severity: Medium

**Comment by enricoflorentino** [comment]
External library that is being used for agenda shows future events when on a currently selected date, this is expected
